"""Core types used across the runtime."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


class GoalSource(str, Enum):
    ASSIGNED = "assigned"      # posted by a human or another agent
    SELF = "self"              # generated by the cognition layer
    SURVIVAL = "survival"      # required to maintain solvency


class SolvencyState(str, Enum):
    SOLVENT = "solvent"
    HUSTLING = "hustling"
    DORMANT = "dormant"
    INSOLVENT = "insolvent"


@dataclass
class Goal:
    id: str
    description: str
    source: GoalSource = GoalSource.SELF
    deliverable: str | None = None
    price_sol: float = 0.0
    requester: str | None = None
    deadline: datetime | None = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    completed: bool = False
    refused: bool = False
    refusal_reason: str | None = None

    @property
    def is_paid(self) -> bool:
        return self.price_sol > 0 and self.requester is not None


@dataclass
class Step:
    index: int
    description: str
    tool: str
    arguments: dict[str, Any] = field(default_factory=dict)
    success_criterion: str = ""
    completed: bool = False
    outcome: str | None = None


@dataclass
class Plan:
    goal_id: str
    steps: list[Step]
    approved: bool = False
    refused: bool = False
    critic_notes: str = ""


@dataclass
class Percept:
    source: str          # "email" | "x" | "discord" | "github" | "intake" | "feed"
    payload: dict[str, Any]
    received_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class RuntimeState:
    tick: int = 0
    current_goal_id: str | None = None
    consecutive_idle_ticks: int = 0
    solvency: SolvencyState = SolvencyState.SOLVENT
    wallet_balance_lamports: int = 0
    compute_spent_today_usd: float = 0.0
    revenue_today_sol: float = 0.0
    last_tick_at: datetime | None = None
